
package view;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import entity.Client;
import entity.Computer;

public class ClientView extends javax.swing.JFrame {

    /**
     * Creates new form ClientView
     */
    private String[] columnNames = new String[] {
            "ID", "Tên", "Tuổi", "Tài khoản", "Giảm giá"
    };
    private String[] comColumnNames = new String[] {
        "ID", "Model", "Giá máy", "Thời gian", "Người dùng"
    };

    public ClientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        remainLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        remainField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        addClientBtn = new javax.swing.JButton();
        editClientBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        deleteClientBtn = new javax.swing.JButton();
        sortClientNameBtn = new javax.swing.JButton();
        sortClientIDBtn = new javax.swing.JButton();
        staticBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        remainSearchField1 = new javax.swing.JTextField();
        nameSearchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        remainSearchField2 = new javax.swing.JTextField();
        remainSearchBtn = new javax.swing.JButton();
        nameSearchBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        idLabel1 = new javax.swing.JLabel();
        idComField = new javax.swing.JTextField();
        idLabel2 = new javax.swing.JLabel();
        modelComField = new javax.swing.JTextField();
        idLabel3 = new javax.swing.JLabel();
        priceComField = new javax.swing.JTextField();
        idLabel4 = new javax.swing.JLabel();
        timeComField = new javax.swing.JTextField();
        idLabel5 = new javax.swing.JLabel();
        userComField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        comTable = new javax.swing.JTable();
        addComBtn = new javax.swing.JButton();
        editComBtn = new javax.swing.JButton();
        deleteComBtn = new javax.swing.JButton();
        clearComBtn = new javax.swing.JButton();
        sortUsingComBtn = new javax.swing.JButton();
        sortIdleComBtn = new javax.swing.JButton();
        comNameSearchField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comPriceSearchField1 = new javax.swing.JTextField();
        comPriceSearchField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comPriceSearchBtn = new javax.swing.JButton();
        ComNameSearchBtn = new javax.swing.JButton();
        rentComBtn = new javax.swing.JButton();
        returnComBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("quản lý khách hàng"); // NOI18N
        setResizable(false);

        idLabel.setText("ID");

        nameLabel.setText("Tên");

        ageLabel.setText("Tuổi");

        remainLabel.setText("Tài khoản");

        discountLabel.setText("Giảm giá");

        discountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountFieldActionPerformed(evt);
            }
        });

        remainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainFieldActionPerformed(evt);
            }
        });

        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Tuổi", "Tài khoản", "Giảm giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clientTable);

        addClientBtn.setText("Thêm");
        addClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientBtnActionPerformed(evt);
            }
        });

        editClientBtn.setText("Sửa");
        editClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClientBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        deleteClientBtn.setText("Xóa");
        deleteClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClientBtnActionPerformed(evt);
            }
        });

        sortClientNameBtn.setText("Sắp xếp theo tên");
        sortClientNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortClientNameBtnActionPerformed(evt);
            }
        });

        sortClientIDBtn.setText("Sắp xếp theo ID");
        sortClientIDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortClientIDBtnActionPerformed(evt);
            }
        });

        staticBtn.setText("Thống kê");
        staticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staticBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("From");

        remainSearchField1.setText("0");
        remainSearchField1.setToolTipText("Nhập tên cần tìm");
        remainSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainSearchField1ActionPerformed(evt);
            }
        });

        nameSearchField.setToolTipText("Nhập tên cần tìm");
        nameSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("To");

        remainSearchField2.setToolTipText("Nhập tên cần tìm");
        remainSearchField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainSearchField2ActionPerformed(evt);
            }
        });

        remainSearchBtn.setText("Search by money");

        nameSearchBtn.setText("Search by name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(staticBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(deleteClientBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(addClientBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editClientBtn))
                                            .addComponent(sortClientNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sortClientIDBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(remainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remainField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameSearchField)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(remainSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(remainSearchField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(remainSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editClientBtn)
                            .addComponent(addClientBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteClientBtn)
                            .addComponent(clearBtn))
                        .addGap(36, 36, 36)
                        .addComponent(sortClientNameBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(sortClientIDBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staticBtn)
                    .addComponent(jLabel1)
                    .addComponent(remainSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainSearchField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(remainSearchBtn))
                .addGap(68, 68, 68))
        );

        jTabbedPane2.addTab("Khách hàng", jPanel3);

        idLabel1.setText("ID máy");

        idComField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComFieldActionPerformed(evt);
            }
        });

        idLabel2.setText("Model máy");

        modelComField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelComFieldActionPerformed(evt);
            }
        });

        idLabel3.setText("Giá máy");

        priceComField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceComFieldActionPerformed(evt);
            }
        });

        idLabel4.setText("Thời gian");

        timeComField.setText("0");
        timeComField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeComFieldActionPerformed(evt);
            }
        });

        idLabel5.setText("Người dùng");

        userComField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComFieldActionPerformed(evt);
            }
        });

        comTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID máy", "Model", "Giá máy", "Thời gian", "Người dùng"
            }
        ));
        jScrollPane2.setViewportView(comTable);

        addComBtn.setText("Thêm máy");
        addComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComBtnActionPerformed(evt);
            }
        });

        editComBtn.setText("Sửa máy");
        editComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editComBtnActionPerformed(evt);
            }
        });

        deleteComBtn.setText("Xóa máy");
        deleteComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteComBtnActionPerformed(evt);
            }
        });

        clearComBtn.setText("Clear");
        clearComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearComBtnActionPerformed(evt);
            }
        });

        sortUsingComBtn.setText("Máy đang dùng");
        sortUsingComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortUsingComBtnActionPerformed(evt);
            }
        });

        sortIdleComBtn.setText("Máy trống");
        sortIdleComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortIdleComBtnActionPerformed(evt);
            }
        });

        comNameSearchField.setToolTipText("Nhập tên cần tìm");
        comNameSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNameSearchFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("From");

        comPriceSearchField1.setText("0");
        comPriceSearchField1.setToolTipText("Nhập tên cần tìm");
        comPriceSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comPriceSearchField1ActionPerformed(evt);
            }
        });

        comPriceSearchField2.setToolTipText("Nhập tên cần tìm");
        comPriceSearchField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comPriceSearchField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("To");

        comPriceSearchBtn.setText("Search by price");

        ComNameSearchBtn.setText("Search by name");

        rentComBtn.setText("Thuê máy");
        rentComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentComBtnActionPerformed(evt);
            }
        });

        returnComBtn.setText("Trả máy");
        returnComBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnComBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idComField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelComField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceComField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeComField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userComField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rentComBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(returnComBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(deleteComBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clearComBtn))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(addComBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editComBtn))
                                .addComponent(sortUsingComBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sortIdleComBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comNameSearchField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comPriceSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comPriceSearchField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComNameSearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comPriceSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idComField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelComField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceComField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeComField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userComField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editComBtn)
                            .addComponent(addComBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteComBtn)
                            .addComponent(clearComBtn))
                        .addGap(18, 18, 18)
                        .addComponent(sortUsingComBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sortIdleComBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComNameSearchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comPriceSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comPriceSearchField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(comPriceSearchBtn))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnComBtn)
                            .addComponent(rentComBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Máy tính", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortClientIDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortClientIDBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortClientIDBtnActionPerformed

    private void remainSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainSearchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainSearchField1ActionPerformed

    private void remainSearchField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainSearchField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainSearchField2ActionPerformed

    private void idComFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idComFieldActionPerformed

    private void modelComFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelComFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelComFieldActionPerformed

    private void priceComFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceComFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceComFieldActionPerformed

    private void timeComFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeComFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeComFieldActionPerformed

    private void userComFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComFieldActionPerformed

    private void addComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addComBtnActionPerformed

    private void editComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editComBtnActionPerformed

    private void deleteComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteComBtnActionPerformed

    private void clearComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearComBtnActionPerformed

    private void sortUsingComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortUsingComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortUsingComBtnActionPerformed

    private void sortIdleComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortIdleComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortIdleComBtnActionPerformed

    private void comNameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNameSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comNameSearchFieldActionPerformed

    private void comPriceSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comPriceSearchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comPriceSearchField1ActionPerformed

    private void comPriceSearchField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comPriceSearchField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comPriceSearchField2ActionPerformed

    private void rentComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentComBtnActionPerformed

    private void returnComBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnComBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnComBtnActionPerformed

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public double findMaxRemaining(List<Client> list){
        int size = list.size();
        double max = 0;
        for(int i = 0; i < size; i++){
            if (list.get(i).getRemain() > max){
                max = list.get(i).getRemain();
            }
        }
        return max;
    }

    public void showListClients(List<Client> list) {
        int size = list.size();
        Object[][] clients = new Object[size][5];
        for (int i = 0; i < size; i++) {
            clients[i][0] = list.get(i).getId();
            clients[i][1] = list.get(i).getName();
            clients[i][2] = list.get(i).getAge();
            clients[i][3] = list.get(i).getRemain();
            clients[i][4] = list.get(i).getDiscount();
        }
        clientTable.setModel(new DefaultTableModel(clients, columnNames));
        this.remainSearchField2.setText("" + findMaxRemaining(list));
    }

    public void showListComputers(List<Computer> list){
        int size = list.size();
        Object[][] computers = new Object[size][5];
        for(int i = 0; i < size; i++){
            computers[i][0] = list.get(i).getId();
            computers[i][1] = list.get(i).getModel();
            computers[i][2] = list.get(i).getPrice();
            computers[i][3] = list.get(i).getUsedTime();
            computers[i][4] = list.get(i).getClientName();
        }
        comTable.setModel(new DefaultTableModel(computers, comColumnNames));
    }

    public void fillClientfromSelectedRow() {
        int row = clientTable.getSelectedRow();
        if (row >= 0) {
            idField.setText(clientTable.getModel().getValueAt(row, 0).toString());
            nameField.setText(clientTable.getModel().getValueAt(row, 1).toString());
            ageField.setText(clientTable.getModel().getValueAt(row, 2).toString());
            remainField.setText(clientTable.getModel().getValueAt(row, 3).toString());
            discountField.setText(clientTable.getModel().getValueAt(row, 4).toString());
            editClientBtn.setEnabled(true);
            deleteClientBtn.setEnabled(true);
            addClientBtn.setEnabled(false);
        }
    }

    public void fillComputerfromSelectedRow(){
        int row = comTable.getSelectedRow();
        if (row >= 0){
            idComField.setText(comTable.getModel().getValueAt(row, 0).toString());
            modelComField.setText(comTable.getModel().getValueAt(row, 1).toString());
            priceComField.setText(comTable.getModel().getValueAt(row, 2).toString());
            timeComField.setText(comTable.getModel().getValueAt(row, 3).toString());
            userComField.setText(comTable.getModel().getValueAt(row, 4).toString());
            editComBtn.setEnabled(true);
            deleteComBtn.setEnabled(true);
            addComBtn.setEnabled(false);

            if(!comTable.getModel().getValueAt(row, 4).toString().isEmpty()){
                returnComBtn.setEnabled(true);
                rentComBtn.setEnabled(false);
                timeComField.setEditable(false);
                userComField.setEditable(false);
            }
            else{
                returnComBtn.setEnabled(false);
                rentComBtn.setEnabled(true);
                timeComField.setEditable(true);
                userComField.setEditable(true);
            }
        }
    }

    public void clearClientInfo() {
        idField.setText("");
        nameField.setText("");
        ageField.setText("");
        remainField.setText("");
        discountField.setText("");
        editClientBtn.setEnabled(false);
        deleteClientBtn.setEnabled(false);
        addClientBtn.setEnabled(true);
    }

    public void clearComInfo() {
        idComField.setText("");
        modelComField.setText("");
        priceComField.setText("");
        timeComField.setText("");
        userComField.setText("");
        editComBtn.setEnabled(false);
        deleteComBtn.setEnabled(false);
        addComBtn.setEnabled(true);
    }

    public void showClient(Client client) {
        fillClientfromSelectedRow();
        idField.setText("" + client.getId());
        nameField.setText(client.getName());
        ageField.setText("" + client.getAge());
        remainField.setText("" + client.getRemain());
        discountField.setText("" + client.getDiscount());
        editClientBtn.setEnabled(true);
        deleteClientBtn.setEnabled(true);
        addClientBtn.setEnabled(false);
    }

    public void showCom(Computer computer) {
        fillComputerfromSelectedRow();
        idComField.setText("" + computer.getId());
        modelComField.setText(computer.getModel());
        priceComField.setText("" + computer.getPrice());
        timeComField.setText("" + computer.getUsedTime());
        userComField.setText(computer.getClientName());
        editComBtn.setEnabled(true);
        deleteComBtn.setEnabled(true);
        addComBtn.setEnabled(false);
    }

    public Client getClientInfo() {
        if (!validateName() || !validateAge() || !validateRemain() || !validateDiscount())
            return null;

        try {
            Client client = new Client();
            if (idField.getText() != null && !"".equals(idField.getText())) {
                client.setId(Integer.parseInt(idField.getText()));
            }
            client.setName(nameField.getText());
            client.setAge(Integer.parseInt(ageField.getText()));
            client.setRemain(Double.parseDouble(remainField.getText()));
            client.setDiscount(Double.parseDouble(discountField.getText()));
            return client;
        } catch (Exception e) {
            e.printStackTrace();
            showMessage("An error occurred while creating the client");
        }
        return null;
    }

    public Computer getComputerInfo() {
        if (!validateComModel() || !validatePrice())
            return null;

        try {
            Computer computer = new Computer();
            if (idComField.getText() != null && !"".equals(idComField.getText())) {
                computer.setId(Integer.parseInt(idComField.getText()));
            }
            computer.setModel(modelComField.getText());
            computer.setPrice(Double.parseDouble(priceComField.getText()));
            computer.setUsedTime(Double.parseDouble(timeComField.getText()));
            computer.setClientName(userComField.getText());
            return computer;
        } catch (Exception e) {
            e.printStackTrace();
            showMessage("An error occurred while creating the computer");
        }
        return null;
    }

    public String getNameSearchField() {
        return this.nameSearchField.getText();
    }

    public String getComModelSearchField(){
        return this.modelComField.getText();
    }

    public String getRemainSearchField1(){
        return this.remainSearchField1.getText();
    }

    public String getComPriceSearchField1(){
        return this.comPriceSearchField1.getText();
    }

    public String getRemainSearchField2(){
        return this.remainSearchField2.getText();
    }

    public String getComPriceSearchField2(){
        return this.comPriceSearchField2.getText();
    }

    public double getTimeRented(){
        return Double.parseDouble(timeComField.getText());
    }

    public String getUserCom(){
        return this.userComField.getText();
    }
    private boolean validateName() {
        String name = nameField.getText();
        if (name == null || "".equals(name.trim())) {
            nameField.requestFocus();
            showMessage("Name không được trống.");
            return false;
        }
        return true;
    }

    private boolean validateComModel() {
        String name = modelComField.getText();
        if (name == null || "".equals(name.trim())) {
            modelComField.requestFocus();
            showMessage("Model không được trống.");
            return false;
        }
        return true;
    }

    private boolean validateAge() {
        try {
            Integer age = Integer.parseInt(ageField.getText().trim());
            if (age < 0 || age > 100) {
                ageField.requestFocus();
                showMessage("Age không hợp lệ, age nên trong khoảng 0 đến 100.");
                return false;
            }
        } catch (Exception e) {
            ageField.requestFocus();
            showMessage("Age không hợp lệ!");
            return false;
        }
        return true;
    }

    private boolean validatePrice() {
        try {
            Double price = Double.parseDouble(priceComField.getText().trim());
            if (price < 0) {
                priceComField.requestFocus();
                showMessage("Price không hợp lệ");
                return false;
            }
        } catch (Exception e) {
            priceComField.requestFocus();
            showMessage("Price không hợp lệ!");
            return false;
        }
        return true;
    }

    private boolean validateRemain() {
        try {
            Double remain = Double.parseDouble(remainField.getText().trim());
            if (remain < 0) {
                remainField.requestFocus();
                showMessage("Remain không hợp lệ, số tiền phải lớn hơn 0.");
                return false;
            }
        } catch (Exception e) {
            remainField.requestFocus();
            showMessage("Remain không hợp lệ!");
            return false;
        }
        return true;
    }

    // private boolean validateTime() {
    //     try {
    //         Double time = Double.parseDouble(timeComField.getText().trim());
    //         if (time < 0) {
    //             timeComField.requestFocus();
    //             showMessage("Time không hợp lệ");
    //             return false;
    //         }
    //     } catch (Exception e) {
    //         timeComField.requestFocus();
    //         showMessage("Time không hợp lệ");
    //         return false;
    //     }
    //     return true;
    // }

    private boolean validateDiscount() {
        try {
            Double discount = Double.parseDouble(discountField.getText().trim());
            if (discount < 0 || discount > 100) {
                ageField.requestFocus();
                showMessage("Discount không hợp lệ, discount phải lớn hơn 0 và nhỏ hơn 100.");
                return false;
            }
        } catch (Exception e) {
            discountField.requestFocus();
            showMessage("Discount không hợp lệ!");
            return false;
        }
        return true;
    }

    public void actionPerformed(ActionEvent e) {
    }

    public void valueChanged(ListSelectionEvent e) {
    }

    public void addAddClientListener(ActionListener listener) {
        addClientBtn.addActionListener(listener);
    }

    public void addEditClientListener(ActionListener listener) {
        editClientBtn.addActionListener(listener);
    }

    public void addDeleteClientListener(ActionListener listener) {
        deleteClientBtn.addActionListener(listener);
    }

    public void addClearListener(ActionListener listener) {
        clearBtn.addActionListener(listener);
    }

    public void addSortClientNameListener(ActionListener listener) {
        sortClientNameBtn.addActionListener(listener);
    }

    public void addSortClientIDListener(ActionListener listener){
        sortClientIDBtn.addActionListener(listener);
    }

    public void addListClientSelectionListener(ListSelectionListener listener) {
        clientTable.getSelectionModel().addListSelectionListener(listener);
    }

    public void addSearchListener(ActionListener listener) {
        nameSearchBtn.addActionListener(listener);
    }

    public void addRemainSearchListener(ActionListener listener){
        remainSearchBtn.addActionListener(listener);
    }

    public void addAddComListener(ActionListener listener){
        addComBtn.addActionListener(listener);
    }

    public void addEditComListener(ActionListener listener){
        editComBtn.addActionListener(listener);
    }

    public void addDeleteComListener(ActionListener listener){
        deleteComBtn.addActionListener(listener);
    }

    public void addClearComListener(ActionListener listener){
        clearComBtn.addActionListener(listener);
    }

    public void addSortIdleComListener(ActionListener listener){
        sortIdleComBtn.addActionListener(listener);
    }

    public void addSortUsingComListener(ActionListener listener){
        sortUsingComBtn.addActionListener(listener);
    }

    public void addListComSelectionListener(ListSelectionListener listener) {
        comTable.getSelectionModel().addListSelectionListener(listener);
    }

    public void addReturnComListener(ActionListener listener){
        returnComBtn.addActionListener(listener);
    }

    public void addRentComListener(ActionListener listener){
        rentComBtn.addActionListener(listener);
    }

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_idFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameFieldActionPerformed

    private void addClientBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addClientBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_addClientBtnActionPerformed

    private void editClientBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editClientBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_editClientBtnActionPerformed

    private void nameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_searchFieldActionPerformed

    private void deleteClientBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteClientBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_deleteClientBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_clearBtnActionPerformed

    private void sortClientNameBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sortClientNameBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_sortClientNameBtnActionPerformed

    private void staticBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serviceBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_serviceBtnActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ageFieldActionPerformed

    private void remainFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_remainFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_remainFieldActionPerformed

    private void discountFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_discountFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_discountFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComNameSearchBtn;
    private javax.swing.JButton addClientBtn;
    private javax.swing.JButton addComBtn;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearComBtn;
    private javax.swing.JTable clientTable;
    private javax.swing.JTextField comNameSearchField;
    private javax.swing.JButton comPriceSearchBtn;
    private javax.swing.JTextField comPriceSearchField1;
    private javax.swing.JTextField comPriceSearchField2;
    private javax.swing.JTable comTable;
    private javax.swing.JButton deleteClientBtn;
    private javax.swing.JButton deleteComBtn;
    private javax.swing.JTextField discountField;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JButton editClientBtn;
    private javax.swing.JButton editComBtn;
    private javax.swing.JTextField idComField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JLabel idLabel3;
    private javax.swing.JLabel idLabel4;
    private javax.swing.JLabel idLabel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField modelComField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton nameSearchBtn;
    private javax.swing.JTextField nameSearchField;
    private javax.swing.JTextField priceComField;
    private javax.swing.JTextField remainField;
    private javax.swing.JLabel remainLabel;
    private javax.swing.JButton remainSearchBtn;
    private javax.swing.JTextField remainSearchField1;
    private javax.swing.JTextField remainSearchField2;
    private javax.swing.JButton rentComBtn;
    private javax.swing.JButton returnComBtn;
    private javax.swing.JButton sortClientIDBtn;
    private javax.swing.JButton sortClientNameBtn;
    private javax.swing.JButton sortIdleComBtn;
    private javax.swing.JButton sortUsingComBtn;
    private javax.swing.JButton staticBtn;
    private javax.swing.JTextField timeComField;
    private javax.swing.JTextField userComField;
    // End of variables declaration//GEN-END:variables
}
